apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebsidp-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: ebsidp
  template:
    metadata:
      labels:
        app: ebsidp
    spec:
      terminationGracePeriodSeconds: 30
      hostname: ebsidpinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: ebsidp
        image: thushi2007/ebsidp:v4
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - name: ebsidp
          mountPath: /root/.aspnet/DataProtection-Keys
        env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: APPVERSION
              value: "78654"
            - name: Secure__SqlConnectionString
              valueFrom:
                secretKeyRef:
                    name: ebsidp-sqlcon
                    key: SQLCON
      volumes:
      - name: ebsidp
        persistentVolumeClaim:
          claimName: ebsidp-data
---
apiVersion: v1
kind: Service
metadata:
  name: ebsidp-service
spec:
  selector:
    app: ebsidp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 178.128.134.209