apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebsidp-deployment
spec:
  replicas: 3
  selector:
     matchLabels:
       app: ebsidp
  template:
    metadata:
      labels:
        app: ebsidp
    spec:
      terminationGracePeriodSeconds: 30
      hostname: ebsidpinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: ebsidp
        image: thushi2007/ebsidp:v1
        ports:
        - containerPort: 80
        env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: APPVERSION
              value: "78654"
            - name: Secure__SqlConnectionString
              valueFrom:
                secretKeyRef:
                    name: ebsidp-sqlcon
                    key: SQLCON
---
apiVersion: v1
kind: Service
metadata:
  name: ebsidp-service
spec:
  selector:
    app: ebsidp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer